# This topology is testing SignalR in front of a load balancer
name: smartrouter
services:
- name: ingress
  image: nginx
  bindings:
    - protocol: http
      port: 8080
  volumes:
    - source: nginx.conf
      target: /etc/nginx/conf.d/default.conf
- name: sample
  project: Sample/Sample.csproj
  replicas: 2
- name: redis
  image: redis
  bindings:
  - port: 6379
    connectionString: "${host}:${port}"
